services:
  pet_app:
    build:
      context: /opt/pet_telegram_bot/portainer-compose-unpacker/stacks/telegram_support_bot/tg-support-bot
      dockerfile: Dockerfile
    container_name: pet_app_container
    user: root
    restart: always
    depends_on:
      - pet_pgdb
      - pet_redis
    working_dir: /var/www/
    volumes:
      - /opt/pet_telegram_bot/portainer-compose-unpacker/stacks/telegram_support_bot/tg-support-bot:/var/www
    networks:
      - pet
      - traefik_net # ЗАМЕНИТЕ НА ВАШУ СЕТЬ TRAEFIK
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pet-app.rule=Host(`tele.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.pet-app.entrypoints=websecure"
      - "traefik.http.routers.pet-app.tls=true"
      - "traefik.http.routers.pet-app.tls.certresolver=leresolver" # ЗАМЕНИТЕ НА ВАШ РЕЗОЛВЕР
      - "traefik.http.services.pet-app.loadbalancer.server.port=80"

  pet_pgdb:
    image: postgres:latest
    container_name: pet_pgdb_container
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PGDB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pet

  pet_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pet_pgadmin_container
    restart: always
    depends_on:
      - pet_pgdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - pet
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pet-pgadmin.rule=Host(`pgadmin.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.pet-pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pet-pgadmin.tls=true"
      - "traefik.http.routers.pet-pgadmin.tls.certresolver=leresolver"
      - "traefik.http.services.pet-pgadmin.loadbalancer.server.port=80"

  pet_redis:
    image: redis:latest
    container_name: pet_redis_container
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - pet

  pet_queue:
    build:
      context: /opt/pet_telegram_bot/portainer-compose-unpacker/stacks/telegram_support_bot/tg-support-bot
      dockerfile: Dockerfile
    container_name: pet_queue_container
    restart: always
    depends_on:
      - pet_app
      - pet_redis
    working_dir: /var/www
    volumes:
      - /opt/pet_telegram_bot/portainer-compose-unpacker/stacks/telegram_support_bot/tg-support-bot:/var/www
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    networks:
      - pet

  pet_node:
    build:
      context: /opt/pet_telegram_bot/portainer-compose-unpacker/stacks/telegram_support_bot/tg-support-bot/docker/node
      dockerfile: Dockerfile
    container_name: pet_node_container
    restart: always
    volumes:
      - /opt/pet_telegram_bot/portainer-compose-unpacker/stacks/telegram_support_bot/tg-support-bot/docker/node:/usr/src/app
    depends_on:
      - pet_redis
    networks:
      - pet
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pet-node.rule=Host(`node.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.pet-node.entrypoints=websecure"
      - "traefik.http.routers.pet-node.tls=true"
      - "traefik.http.routers.pet-node.tls.certresolver=leresolver"
      - "traefik.http.services.pet-node.loadbalancer.server.port=3000"

volumes:
  pgdata:

networks:
  pet:
    driver: bridge
  traefik_net:
    external: true # Указываем, что сеть уже создана Traefik-ом
